version: "2"
services:
  worker:
    build: .
    networks:
    - test-newport_newport_network  
    depends_on:
    - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.1
    ports:
      - "9400:9400"
networks:
  test-newport_newport_network:
    external:
      name: test-newport_newport_network