apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: es
  name: es-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: es
    spec:
      containers:
      - image: docker.elastic.co/elasticsearch/elasticsearch:6.4.1
        name: es
        ports:
        - name: es
          containerPort: 9200
          hostPort: 9200