apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: worker
  name: worker-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: worker
    spec:
      containers:
      - image: asia.gcr.io/newport-271215/test-newport-es
        name: worker
        ports:
        - containerPort: 3000
          name: http-server